services:
  - type: web
    name: portfolio
    env: node
    buildCommand: npm install && npm run build  # Install dependencies and build React app
    startCommand: npm run prod  # Use the prod script which runs node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5001
    staticPublishPath: ./build  # Directory containing your React build
    routes:
      - type: rewrite
        source: /admin/*
        destination: /index.html
      - type: rewrite
        source: /static/*
        destination: /static/*
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*
        name: Cache-Control
        value: no-cache
